apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: preprd-majls
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/anveshmuppeda/argo-cd-demo
    targetRevision: preprd
    path: nginx-app

  destination: 
    server: https://kubernetes.default.svc
    namespace: preprd-majls

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true