apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-majls
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/xgenOsama/argocd-poc
    targetRevision: test
    path: nginx-app # Path to the Helm chart in your repository
    helm:
      valueFiles:
        - values_test.yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: test-majls

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true