replicaCount: 0

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  name: "nginx-app"

ingress:
  enabled: false
  default_backend: {}
serviceAccount:
  create: false
autoscaling:
  enabled: false
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
