controller:
  persistence:
    enabled: true
    storageClass: manual
    type: hostPath
    path: /Users/n1x/Sure/argocd/data/argocd-controller  # Path on the host system
    accessMode: ReadWriteOnce
    size: 8Gi # Set the appropriate size for your deployment
server:
  service:
    type: NodePort
  persistence:
    enabled: true
    storageClass: manual
    size: 10Gi
    type: hostPath
    path: /Users/n1x/Sure/argocd/data/argocd-server  # Path on the host system
    accessMode: ReadWriteOnce
  replicas: 1
repoServer:
  persistence:
    enabled: true
    storageClass: manual
    type: hostPath
    path: /Users/n1x/Sure/argocd/data/argocd-repo-server  # Path on the host system
    size: 10Gi
    accessMode: ReadWriteOnce

dex:
  persistence:
    storageClass: manual
    enabled: true
    type: hostPath
    path: /Users/n1x/Sure/argocd/data/argocd-dex  # Path on the host system
    size: 10Gi
    accessMode: ReadWriteOnce
configs:
  rbac:
    policy.default: role:readonly  # Default role for unauthenticated users

    policy.csv: |
      g, user1, role:developer    # Map user1 to the developer role
      g, user2, role:admin        # Map user2 to the admin role

    role.developer: |
      p, role:developer, applications, get, */*, allow
      p, role:developer, applications, sync, */*, allow
      p, role:developer, applications, create, */*, allow
      p, role:developer, applications, delete, */*, allow
      p, role:developer, clusters, get, *, allow
      p, role:developer, repositories, get, *, allow

    role.admin: |
      p, role:admin, *, *, *, allow