apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      initContainers:
        - name: init-html
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              echo "{{ .Values.htmlContent }}" > /usr/share/nginx/html/index.html
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          emptyDir: {}