apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  containers:
    - name: {{ .Chart.Name }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      ports:
        - name: http
          containerPort: 80
          protocol: TCP